openapi: 3.0.3
info:
  title: Revision API
  version: 1.0.0
servers:
  - url: 'https://revision.com'
paths:
  /books:
    get:
      summary : Get all books
      description: Return all books ordered by author
      operationId: getbooks
      parameters:
        - in: query
          name: bookName
          description: Filter the return books by the given name
          required: false
          schema:
            type: string
      responses:
        200:
          description: The returned books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
                properties:
                  id:
                    type: string
                  bookName:
                      type: string

    put:
      summary: Create or update of  a list of books
      operationId: updateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
              properties:
                id:
                  type: string
                bookName:
                  type: string
      responses:
        200:
          description: The created or update books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
                properties:
                  id:
                    type: string
                  bookName:
                    type: string
                  author:
                    type: string

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        code:
          type : string
          format: BOOK001
        bookName:
          type: string
        author:
          type: string
        releaseDate:
          type: string
          format: date

    Topic:
      type: string
      enum:
        - ROMANCE
        - COMEDY
        - OTHER